app/Http/routes.php
<?php

routes/web.php
<?php

Auth::routes(['verify' => true]);

Route::get('/', 'Portal\Controller@index')->name('landing');

Route::group(['prefix' => 'z'], function () {
    Route::resource('projectMilestoneTypes', 'Z\ProjectMilestoneTypeController', ["as" => 'z']);
    Route::resource('clients', 'Z\ClientController', ["as" => 'z']);
    Route::resource('projectOrganizations', 'Z\ProjectOrganizationController', ["as" => 'z']);
    Route::resource('projectTypes', 'Z\ProjectTypeController', ["as" => 'z']);
});


Route::resource('users', 'UserController');

app/Models/Z/Client.php
<?php

namespace App\Models\Z;

use App\Models\Project\Project;
use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Client
 * @package App\Models\Z
 * @version March 11, 2020, 3:48 am +08
 *
 * @property \App\Models\Z\ProjectType parent
 * @property \Illuminate\Database\Eloquent\Collection projects
 * @property string name
 * @property integer parent_id
 */
class Client extends Model
{
    use SoftDeletes;

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';
    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required'
    ];
    public $table = 'z_clients';
    public $fillable = [
        'name',
        'parent_id'
    ];
    protected $dates = ['deleted_at'];
    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'parent_id' => 'integer'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function parent()
    {
        return $this->belongsTo(Client::class, 'parent_id')->withTrashed();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function children()
    {
        return $this->hasMany(Client::class, 'parent_id')->withTrashed();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function projects()
    {
        return $this->hasMany(Project::class, 'client_id')->withTrashed();
    }

}

app/Models/Z/ProjectMilestoneType.php
<?php

namespace App\Models\Z;

use App\Models\Project\Milestone;
use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class ProjectMilestoneType
 * @package App\Models\Z
 * @version March 11, 2020, 3:48 am +08
 *
 * @property \Illuminate\Database\Eloquent\Collection projectMilestones
 * @property string name
 */
class ProjectMilestoneType extends Model
{
    use SoftDeletes;

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';
    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required'
    ];
    public $table = 'z_project_milestone_types';
    public $fillable = [
        'name'
    ];
    protected $dates = ['deleted_at'];
    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function milestones()
    {
        return $this->hasMany(Milestone::class, 'milestone_type_id')->withTrashed();
    }

}

app/Http/Controllers/API/Z/ClientAPIController.php
<?php

namespace App\Http\Controllers\API\Z;

use App\Http\Requests\API\Z\CreateClientAPIRequest;
use App\Http\Requests\API\Z\UpdateClientAPIRequest;
use App\Models\Z\Client;
use Illuminate\Http\Request;
use App\Http\Controllers\AppBaseController;

/**
 * Class ClientController
 * @package App\Http\Controllers\API\Z
 */

class ClientAPIController extends AppBaseController
{
    /**
     * Display a listing of the Client.
     * GET|HEAD /clients
     *
     * @param Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function index(Request $request)
    {
        $query = Client::query();

        if ($request->get('skip')) {
            $query->skip($request->get('skip'));
        }
        if ($request->get('limit')) {
            $query->limit($request->get('limit'));
        }

        $clients = $query->get();

        return $this->sendResponse($clients->toArray(), 'Clients retrieved successfully');
    }

    /**
     * Store a newly created Client in storage.
     * POST /clients
     *
     * @param CreateClientAPIRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function store(CreateClientAPIRequest $request)
    {
        $input = $request->all();

        /** @var Client $client */
        $client = Client::create($input);

        return $this->sendResponse($client->toArray(), 'Client saved successfully');
    }

    /**
     * Display the specified Client.
     * GET|HEAD /clients/{id}
     *
     * @param int $id
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function show($id)
    {
        /** @var Client $client */
        $client = Client::find($id);

        if (empty($client)) {
            return $this->sendError('Client not found');
        }

        return $this->sendResponse($client->toArray(), 'Client retrieved successfully');
    }

    /**
     * Update the specified Client in storage.
     * PUT/PATCH /clients/{id}
     *
     * @param int $id
     * @param UpdateClientAPIRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function update($id, UpdateClientAPIRequest $request)
    {
        /** @var Client $client */
        $client = Client::find($id);

        if (empty($client)) {
            return $this->sendError('Client not found');
        }

        $client->fill($request->all());
        $client->save();

        return $this->sendResponse($client->toArray(), 'Client updated successfully');
    }

    /**
     * Remove the specified Client from storage.
     * DELETE /clients/{id}
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function destroy($id)
    {
        /** @var Client $client */
        $client = Client::find($id);

        if (empty($client)) {
            return $this->sendError('Client not found');
        }

        $client->delete();

        return $this->sendSuccess('Client deleted successfully');
    }
}

app/Http/Controllers/API/Z/ProjectMilestoneTypeAPIController.php
<?php

namespace App\Http\Controllers\API\Z;

use App\Http\Requests\API\Z\CreateProjectMilestoneTypeAPIRequest;
use App\Http\Requests\API\Z\UpdateProjectMilestoneTypeAPIRequest;
use App\Models\Z\ProjectMilestoneType;
use Illuminate\Http\Request;
use App\Http\Controllers\AppBaseController;

/**
 * Class ProjectMilestoneTypeController
 * @package App\Http\Controllers\API\Z
 */

class ProjectMilestoneTypeAPIController extends AppBaseController
{
    /**
     * Display a listing of the ProjectMilestoneType.
     * GET|HEAD /projectMilestoneTypes
     *
     * @param Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function index(Request $request)
    {
        $query = ProjectMilestoneType::query();

        if ($request->get('skip')) {
            $query->skip($request->get('skip'));
        }
        if ($request->get('limit')) {
            $query->limit($request->get('limit'));
        }

        $projectMilestoneTypes = $query->get();

        return $this->sendResponse($projectMilestoneTypes->toArray(), 'Project Milestone Types retrieved successfully');
    }

    /**
     * Store a newly created ProjectMilestoneType in storage.
     * POST /projectMilestoneTypes
     *
     * @param CreateProjectMilestoneTypeAPIRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function store(CreateProjectMilestoneTypeAPIRequest $request)
    {
        $input = $request->all();

        /** @var ProjectMilestoneType $projectMilestoneType */
        $projectMilestoneType = ProjectMilestoneType::create($input);

        return $this->sendResponse($projectMilestoneType->toArray(), 'Project Milestone Type saved successfully');
    }

    /**
     * Display the specified ProjectMilestoneType.
     * GET|HEAD /projectMilestoneTypes/{id}
     *
     * @param int $id
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function show($id)
    {
        /** @var ProjectMilestoneType $projectMilestoneType */
        $projectMilestoneType = ProjectMilestoneType::find($id);

        if (empty($projectMilestoneType)) {
            return $this->sendError('Project Milestone Type not found');
        }

        return $this->sendResponse($projectMilestoneType->toArray(), 'Project Milestone Type retrieved successfully');
    }

    /**
     * Update the specified ProjectMilestoneType in storage.
     * PUT/PATCH /projectMilestoneTypes/{id}
     *
     * @param int $id
     * @param UpdateProjectMilestoneTypeAPIRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function update($id, UpdateProjectMilestoneTypeAPIRequest $request)
    {
        /** @var ProjectMilestoneType $projectMilestoneType */
        $projectMilestoneType = ProjectMilestoneType::find($id);

        if (empty($projectMilestoneType)) {
            return $this->sendError('Project Milestone Type not found');
        }

        $projectMilestoneType->fill($request->all());
        $projectMilestoneType->save();

        return $this->sendResponse($projectMilestoneType->toArray(), 'ProjectMilestoneType updated successfully');
    }

    /**
     * Remove the specified ProjectMilestoneType from storage.
     * DELETE /projectMilestoneTypes/{id}
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function destroy($id)
    {
        /** @var ProjectMilestoneType $projectMilestoneType */
        $projectMilestoneType = ProjectMilestoneType::find($id);

        if (empty($projectMilestoneType)) {
            return $this->sendError('Project Milestone Type not found');
        }

        $projectMilestoneType->delete();

        return $this->sendSuccess('Project Milestone Type deleted successfully');
    }
}

app/Http/Controllers/API/Z/ProjectOrganizationAPIController.php
<?php

namespace App\Http\Controllers\API\Z;

use App\Http\Requests\API\Z\CreateProjectOrganizationAPIRequest;
use App\Http\Requests\API\Z\UpdateProjectOrganizationAPIRequest;
use App\Models\Z\ProjectOrganization;
use Illuminate\Http\Request;
use App\Http\Controllers\AppBaseController;

/**
 * Class ProjectOrganizationController
 * @package App\Http\Controllers\API\Z
 */

class ProjectOrganizationAPIController extends AppBaseController
{
    /**
     * Display a listing of the ProjectOrganization.
     * GET|HEAD /projectOrganizations
     *
     * @param Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function index(Request $request)
    {
        $query = ProjectOrganization::query();

        if ($request->get('skip')) {
            $query->skip($request->get('skip'));
        }
        if ($request->get('limit')) {
            $query->limit($request->get('limit'));
        }

        $projectOrganizations = $query->get();

        return $this->sendResponse($projectOrganizations->toArray(), 'Project Organizations retrieved successfully');
    }

    /**
     * Store a newly created ProjectOrganization in storage.
     * POST /projectOrganizations
     *
     * @param CreateProjectOrganizationAPIRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function store(CreateProjectOrganizationAPIRequest $request)
    {
        $input = $request->all();

        /** @var ProjectOrganization $projectOrganization */
        $projectOrganization = ProjectOrganization::create($input);

        return $this->sendResponse($projectOrganization->toArray(), 'Project Organization saved successfully');
    }

    /**
     * Display the specified ProjectOrganization.
     * GET|HEAD /projectOrganizations/{id}
     *
     * @param int $id
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function show($id)
    {
        /** @var ProjectOrganization $projectOrganization */
        $projectOrganization = ProjectOrganization::find($id);

        if (empty($projectOrganization)) {
            return $this->sendError('Project Organization not found');
        }

        return $this->sendResponse($projectOrganization->toArray(), 'Project Organization retrieved successfully');
    }

    /**
     * Update the specified ProjectOrganization in storage.
     * PUT/PATCH /projectOrganizations/{id}
     *
     * @param int $id
     * @param UpdateProjectOrganizationAPIRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function update($id, UpdateProjectOrganizationAPIRequest $request)
    {
        /** @var ProjectOrganization $projectOrganization */
        $projectOrganization = ProjectOrganization::find($id);

        if (empty($projectOrganization)) {
            return $this->sendError('Project Organization not found');
        }

        $projectOrganization->fill($request->all());
        $projectOrganization->save();

        return $this->sendResponse($projectOrganization->toArray(), 'ProjectOrganization updated successfully');
    }

    /**
     * Remove the specified ProjectOrganization from storage.
     * DELETE /projectOrganizations/{id}
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function destroy($id)
    {
        /** @var ProjectOrganization $projectOrganization */
        $projectOrganization = ProjectOrganization::find($id);

        if (empty($projectOrganization)) {
            return $this->sendError('Project Organization not found');
        }

        $projectOrganization->delete();

        return $this->sendSuccess('Project Organization deleted successfully');
    }
}

app/Http/Controllers/API/Z/ProjectTypeAPIController.php
<?php

namespace App\Http\Controllers\API\Z;

use App\Http\Requests\API\Z\CreateProjectTypeAPIRequest;
use App\Http\Requests\API\Z\UpdateProjectTypeAPIRequest;
use App\Models\Z\ProjectType;
use Illuminate\Http\Request;
use App\Http\Controllers\AppBaseController;

/**
 * Class ProjectTypeController
 * @package App\Http\Controllers\API\Z
 */

class ProjectTypeAPIController extends AppBaseController
{
    /**
     * Display a listing of the ProjectType.
     * GET|HEAD /projectTypes
     *
     * @param Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function index(Request $request)
    {
        $query = ProjectType::query();

        if ($request->get('skip')) {
            $query->skip($request->get('skip'));
        }
        if ($request->get('limit')) {
            $query->limit($request->get('limit'));
        }

        $projectTypes = $query->get();

        return $this->sendResponse($projectTypes->toArray(), 'Project Types retrieved successfully');
    }

    /**
     * Store a newly created ProjectType in storage.
     * POST /projectTypes
     *
     * @param CreateProjectTypeAPIRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function store(CreateProjectTypeAPIRequest $request)
    {
        $input = $request->all();

        /** @var ProjectType $projectType */
        $projectType = ProjectType::create($input);

        return $this->sendResponse($projectType->toArray(), 'Project Type saved successfully');
    }

    /**
     * Display the specified ProjectType.
     * GET|HEAD /projectTypes/{id}
     *
     * @param int $id
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function show($id)
    {
        /** @var ProjectType $projectType */
        $projectType = ProjectType::find($id);

        if (empty($projectType)) {
            return $this->sendError('Project Type not found');
        }

        return $this->sendResponse($projectType->toArray(), 'Project Type retrieved successfully');
    }

    /**
     * Update the specified ProjectType in storage.
     * PUT/PATCH /projectTypes/{id}
     *
     * @param int $id
     * @param UpdateProjectTypeAPIRequest $request
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function update($id, UpdateProjectTypeAPIRequest $request)
    {
        /** @var ProjectType $projectType */
        $projectType = ProjectType::find($id);

        if (empty($projectType)) {
            return $this->sendError('Project Type not found');
        }

        $projectType->fill($request->all());
        $projectType->save();

        return $this->sendResponse($projectType->toArray(), 'ProjectType updated successfully');
    }

    /**
     * Remove the specified ProjectType from storage.
     * DELETE /projectTypes/{id}
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return \Illuminate\Http\JsonResponse
     */

    public function destroy($id)
    {
        /** @var ProjectType $projectType */
        $projectType = ProjectType::find($id);

        if (empty($projectType)) {
            return $this->sendError('Project Type not found');
        }

        $projectType->delete();

        return $this->sendSuccess('Project Type deleted successfully');
    }
}

resources/views/z/project_milestone_types/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Project Milestone Type
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'z.projectMilestoneTypes.store']) !!}

                        @include('z.project_milestone_types.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/z/project_milestone_types/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Project Milestone Type
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($projectMilestoneType, ['route' => ['z.projectMilestoneTypes.update', $projectMilestoneType->id], 'method' => 'patch']) !!}

                        @include('z.project_milestone_types.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/z/project_milestone_types/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('z.projectMilestoneTypes.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/z/project_milestone_types/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Project Milestone Types</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('z.projectMilestoneTypes.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('z.project_milestone_types.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/z/project_milestone_types/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Project Milestone Type
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('z.project_milestone_types.show_fields')
                    <a href="{{ route('z.projectMilestoneTypes.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/z/project_milestone_types/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{{ $projectMilestoneType->name }}</p>
</div>

resources/views/z/project_milestone_types/table.blade.php
<div class="table-responsive">
    <table class="table" id="projectMilestoneTypes-table">
        <thead>
            <tr>
                <th>Name</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($projectMilestoneTypes as $projectMilestoneType)
            <tr>
                <td>{{ $projectMilestoneType->name }}</td>
                <td>
                    {!! Form::open(['route' => ['z.projectMilestoneTypes.destroy', $projectMilestoneType->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('z.projectMilestoneTypes.show', [$projectMilestoneType->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('z.projectMilestoneTypes.edit', [$projectMilestoneType->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>